name: CI Demo

on: 
  pull_request:
    branches: 
      - master

jobs:
  lint:
    name: Lint PHP, and validate Composer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@7.3
        with:
          dir: './web'

  build:
    name: Install dependencies, and build project
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - continue-on-error: false
        name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
