name: CI Demo

on: 
  pull_request:
    branches: 
      - master

jobs:
  lint:
    name: Lint PHP, and validate Composer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - uses: michaelw90/PHP-Lint@master

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - continue-on-error: false

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
