name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          # '0' indicates all commit history.
          fetch-depth: '0'

      -
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.23.0
        env:
            GITHUB_TOKEN: ${{ secrets.UNITY_GITHUB_PAT }}
            DEFAULT_BUMP: patch
            WITH_V: false

      - 
        name: Merge master to production
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          label_name: 'Merge master to production'
          target_branch: 'production'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
