name: Merge master to production

on:
  pull_request:
    types:
      - labeled
    branches:
      - master

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v2

      - 
        name: Merge branch
        uses: devmasx/merge-branch@v1.1.0
        with:
          label_name: 'Merge master to production'
          target_branch: 'production'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
