name: Bump version

# Bumping
# 
# Manual Bumping: Any commit message that includes `#major`, `#minor`, 
# or `#patch` will trigger the respective version bump. If two or more are 
# present, the highest-ranking one will take precedence.
# 
# Automatic Bumping: If no `#major`, `#minor` or `#patch` tag is contained in 
# the commit messages, it will bump whichever DEFAULT_BUMP is set to (which is
# minor by default).
# 
# Note: This action will not bump the tag if the HEAD commit has already been 
# tagged.
# 
# Workflow
# 
# * Add this action to your repo
# * Commit some changes
# * Either push to master or open a PR
# * On push (or merge) to master, the action will:
#   * Get latest tag
#   * Bump tag with minor version unless any commit message contains #major or #patch
#   * Pushes tag to github

on:
  push:
    branches:
      - master # Push events on master branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.18.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        DEFAULT_BUMP: patch
